'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const bytes=fs.readFileSync(`${__dirname}/pages-direct.wasm`);
(async()=>{
 const memory=new WebAssembly.Memory({initial:4});
 const helper=new WebAssembly.Instance(new WebAssembly.Module(bytes),{ruffle:{memory}}).exports;
 helper.memory.grow(4);
 const incoming=new Uint8Array(memory.buffer);
 incoming[0]=1;incoming[65535]=255;incoming[65536]=128;incoming[4*65536-1]=128;
 assert.equal(helper.changed_pages(incoming.length),4);
 assert.deepEqual(Array.from(new Uint32Array(helper.memory.buffer,incoming.length,4)),[0,3,4,15]);
 new Uint8Array(helper.memory.buffer).set(incoming);
 assert.equal(helper.changed_pages(incoming.length),0);
 const env={RuffleRollback:{},document:{currentScript:{src:'http://localhost/pages-direct.js'}},URL,WebAssembly,Uint8Array,Uint32Array,fetch:async()=>({arrayBuffer:async()=>bytes})};
 vm.runInNewContext(fs.readFileSync(`${__dirname}/pages-direct.js`,'utf8'),env);
 await env.RuffleRollback.pagesReady;
 const store=env.RuffleRollback.memoryStore;
 const a=store.capture(memory);
 incoming[90000]=99;
 const b=store.capture(memory);
 incoming[90000]=11;incoming[0]=42;
 const c=store.capture(memory);
 store.restore(memory,a);assert.equal(incoming[0],1);assert.equal(incoming[90000],0);
 const d=store.capture(memory);
 store.release(a);store.release(c);
 store.restore(memory,b);assert.equal(incoming[0],1);assert.equal(incoming[90000],99);
 store.restore(memory,d);assert.equal(incoming[90000],0);
 store.release(b);store.release(d);
 const allocatedTables=store.inspect().allocatedPageTables;
 const reused=store.capture(memory);store.release(reused);
 const stats=store.inspect();assert(stats.pooledPages>0);assert.equal(stats.captures,5);
 assert.equal(stats.allocatedPageTables,allocatedTables,'Released page tables are reused without allocating');
 assert(stats.pooledPageTables>0);
 console.log('PASS direct-memory SIMD comparison, immutable shared snapshots, discarded futures and buffer reuse',stats);
})().catch(e=>{console.error(e);process.exitCode=1;});
